name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: 谢谢狗头🐶
        run: echo "                       ::" && echo "                      :;J7, :,                        ::;7:" && echo "                      ,ivYi, ,                       ;LLLFS:" && echo "                      :iv7Yi                       :7ri;j5PL" && echo "                     ,:ivYLvr                    ,ivrrirrY2X," && echo "                     :;r@Wwz.7r:                :ivu@kexianli." && echo "                    :iL7::,:::iiirii:ii;::::,,irvF7rvvLujL7ur" && echo "                   ri::,:,::i:iiiiiii:i:irrv177JX7rYXqZEkvv17" && echo "                ;i:, , ::::iirrririi:i:::iiir2XXvii;L8OGJr71i" && echo "              :,, ,,:   ,::ir@mingyi.irii:i:::j1jri7ZBOS7ivv," && echo "                 ,::,    ::rv77iiiriii:iii:i::,rvLq@huhao.Li" && echo "             ,,      ,, ,:ir7ir::,:::i;ir:::i:i::rSGGYri712:" && echo "           :::  ,v7r:: ::rrv77:, ,, ,:i7rrii:::::, ir7ri7Lri" && echo "          ,     2OBBOi,iiir;r::        ,irriiii::,, ,iv7Luur:" && echo "        ,,     i78MBBi,:,:::,:,  :7FSL: ,iriii:::i::,,:rLqXv::" && echo "        :      iuMMP: :,:::,:ii;2GY7OBB0viiii:i:iii:i:::iJqL;::" && echo "       ,     ::::i   ,,,,, ::LuBBu BBBBBErii:i:i:i:i:i:i:r77ii" && echo "      ,       :       , ,,:::rruBZ1MBBqi, :,,,:::,::::::iiriri:" && echo "     ,               ,,,,::::i:  @arqiao.       ,:,, ,:::ii;i7:" && echo "    :,       rjujLYLi   ,,:::::,:::::::::,,   ,:i,:,,,,,::i:iii" && echo "    ::      BBBBBBBBB0,    ,,::: , ,:::::: ,      ,,,, ,,:::::::" && echo "    i,  ,  ,8BMMBBBBBBi     ,,:,,     ,,, , ,   , , , :,::ii::i::" && echo "    i   ,,:;u0MBMOG1L:::i::::::  ,,,::,   ,,, ::::::i:i:iirii:i:i:" && echo "    :    ,iuUuuXUkFu7i:iii:i:::, :,:,: ::::::::i:i:::::iirr7iiri::" && echo "    :     :rk@Yizero.i:::::, ,:ii:::::::i:::::i::,::::iirrriiiri::," && echo "     :      5BMBBBBBBSr:,::rv2kuii:::iii::,:i:,, , ,,:,:i@petermu.," && echo "          , :r50EZ8MBBBBGOBBBZP7::::i::,:::::,: :,:,::i;rrririiii::" && echo "              :jujYY7LS0ujJL7r::,::i::,::::::::::::::iirirrrrrrr:ii:" && echo "           ,:  :@liuzeqi-code,,,::::i:i:::::,,::::::iir;ii;7v77;ii;i," && echo "           ,,,     ,,:,::::::i:iiiii:i::::,, ::::iiiir@xingjief.r;7:i," && echo "        , , ,,,:,,::::::::iiiiiiiiii:,:,:::::::::iiir;ri7vL77rrirri::" && echo "         :,, , ::::::::i:::i:::i:i::,,,,,:,::i:i:::iir;@liuzeqi.top:::" && echo "--------------------------------------------------------------------------" && echo "                                 狗头保佑" && echo "                              编译永远不出BUG" && echo "                         快在Discussions里说谢谢狗头"       
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches
      - name: Build
        run: ./gradlew createMojmapBundlerJar
      - name: Build
        run: ./gradlew createMojmapPaperclipJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: 114514
          path: folia-server/build/libs/*.jar
