name: Patch and Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "set running OS"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.environment }}
    steps:
      - name: check OS
        run: echo "running on ${{ inputs.environment }}"
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches
      - name: Build
        run: ./gradlew createMojmapBundlerJar
      - name: Build
        run: ./gradlew createMojmapPaperclipJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: folia-server
          path: folia-server/build/libs/*.jar
